"""Remove text column from document

Revision ID: 72c70ab98f7d
Revises: 
Create Date: 2024-10-07 10:27:49.715547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72c70ab98f7d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accommodation_industry', schema=None) as batch_op:
        batch_op.drop_constraint('FK__accommoda__accom__13F1F5EB', type_='foreignkey')
        batch_op.drop_constraint('FK__accommoda__indus__14E61A24', type_='foreignkey')
        batch_op.create_foreign_key(None, 'accommodations', ['accommodation_id'], ['accommodation_id'])
        batch_op.create_foreign_key(None, 'industries', ['industry_id'], ['industry_id'])

    with op.batch_alter_table('accommodation_injury_location', schema=None) as batch_op:
        batch_op.drop_constraint('FK__accommoda__accom__17C286CF', type_='foreignkey')
        batch_op.drop_constraint('FK__accommoda__injur__18B6AB08', type_='foreignkey')
        batch_op.create_foreign_key(None, 'injury_locations', ['injury_location_id'], ['injury_location_id'])
        batch_op.create_foreign_key(None, 'accommodations', ['accommodation_id'], ['accommodation_id'])

    with op.batch_alter_table('accommodation_injury_nature', schema=None) as batch_op:
        batch_op.drop_constraint('FK__accommoda__injur__1C873BEC', type_='foreignkey')
        batch_op.drop_constraint('FK__accommoda__accom__1B9317B3', type_='foreignkey')
        batch_op.create_foreign_key(None, 'accommodations', ['accommodation_id'], ['accommodation_id'])
        batch_op.create_foreign_key(None, 'injury_natures', ['injury_nature_id'], ['injury_nature_id'])

    with op.batch_alter_table('accommodations', schema=None) as batch_op:
        batch_op.alter_column('accommodation_name',
               existing_type=sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('accommodation_description',
               existing_type=sa.TEXT(length=2147483647, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_constraint('FK__accommoda__docum__0B5CAFEA', type_='foreignkey')
        batch_op.create_foreign_key(None, 'documents', ['document_id'], ['document_id'])

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('document_name',
               existing_type=sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('document_description',
               existing_type=sa.TEXT(length=2147483647, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('url',
               existing_type=sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_column('text')

    with op.batch_alter_table('industries', schema=None) as batch_op:
        batch_op.alter_column('industry_name',
               existing_type=sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(),
               existing_nullable=False)

    with op.batch_alter_table('injury_locations', schema=None) as batch_op:
        batch_op.alter_column('injury_location_name',
               existing_type=sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(),
               existing_nullable=False)

    with op.batch_alter_table('injury_natures', schema=None) as batch_op:
        batch_op.alter_column('injury_nature_name',
               existing_type=sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.drop_column('injury_nature_description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('injury_natures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('injury_nature_description', sa.TEXT(length=2147483647, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.alter_column('injury_nature_name',
               existing_type=sa.String(),
               type_=sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)

    with op.batch_alter_table('injury_locations', schema=None) as batch_op:
        batch_op.alter_column('injury_location_name',
               existing_type=sa.String(),
               type_=sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)

    with op.batch_alter_table('industries', schema=None) as batch_op:
        batch_op.alter_column('industry_name',
               existing_type=sa.String(),
               type_=sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.TEXT(length=2147483647, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.alter_column('url',
               existing_type=sa.String(),
               type_=sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('document_description',
               existing_type=sa.Text(),
               type_=sa.TEXT(length=2147483647, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('document_name',
               existing_type=sa.String(),
               type_=sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)

    with op.batch_alter_table('accommodations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('FK__accommoda__docum__0B5CAFEA', 'documents', ['document_id'], ['document_id'], ondelete='SET NULL')
        batch_op.alter_column('accommodation_description',
               existing_type=sa.Text(),
               type_=sa.TEXT(length=2147483647, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('accommodation_name',
               existing_type=sa.String(),
               type_=sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)

    with op.batch_alter_table('accommodation_injury_nature', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('FK__accommoda__accom__1B9317B3', 'accommodations', ['accommodation_id'], ['accommodation_id'], ondelete='CASCADE')
        batch_op.create_foreign_key('FK__accommoda__injur__1C873BEC', 'injury_natures', ['injury_nature_id'], ['injury_nature_id'], ondelete='CASCADE')

    with op.batch_alter_table('accommodation_injury_location', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('FK__accommoda__injur__18B6AB08', 'injury_locations', ['injury_location_id'], ['injury_location_id'], ondelete='CASCADE')
        batch_op.create_foreign_key('FK__accommoda__accom__17C286CF', 'accommodations', ['accommodation_id'], ['accommodation_id'], ondelete='CASCADE')

    with op.batch_alter_table('accommodation_industry', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('FK__accommoda__indus__14E61A24', 'industries', ['industry_id'], ['industry_id'], ondelete='CASCADE')
        batch_op.create_foreign_key('FK__accommoda__accom__13F1F5EB', 'accommodations', ['accommodation_id'], ['accommodation_id'], ondelete='CASCADE')

    # ### end Alembic commands ###
